name: Java CI con pruebas

# Se ejecuta cuando hay push o pull request a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar código y pruebas
      run: javac -cp .:libs/junit-4.13.2.jar:libs/hamcrest-core-1.3.jar src/Calculadora.java test/CalculadoraTest.java

    - name: Ejecutar pruebas JUnit
      run: java -cp .:libs/junit-4.13.2.jar:libs/hamcrest-core-1.3.jar org.junit.runner.JUnitCore CalculadoraTest
